### ISSUE TITLE
[SUGGESTION] Collaborate with LosslessCut

### ISSUE THREAD

**Issue by MarcoRavich** [rahulvenugopal/snip-er#1]
Hi there, your project seems promising so I suggest you to "keep an eye" on Mikael Finstad's LosslessCut, wich is a mature "swiss army knife of lossless video/audio editing":

https://github.com/mifi/lossless-cut

Hope that inspires !

**Comment by rahulvenugopal** [comment]
Thanks a lot for the suggestion. This tool looks great. Will check it out
